"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ON_CODESPACE = os.getenv("ON_CODESPACE", "False") == "True"
ON_RAILWAY = os.getenv("ON_RAILWAY", "False") == "True"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = []
if ON_RAILWAY:
    ALLOWED_HOSTS += [
        '.railway.app',
    ]
else:
    ALLOWED_HOSTS += [
        '127.0.0.1',
        'localhost',
    ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',      # <--- For DRF
    'corsheaders',         # <--- For CORS Headers
    
    # ALLAUTH APPS
    'allauth',
    'allauth.account',
    'allauth.headless',  # Headless mode
    
    # Local apps
    'api',                 # <--- Local
    'commando',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # for cors header
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'allauth.account.middleware.AccountMiddleware', # allauth
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 1. Fetch the URL using os.getenv, defaulting to an empty string if missing
database_url = os.getenv('DATABASE_URL', '')

if database_url:
    # 2. If the URL exists, parse it and use PostgreSQL
    tmpPostgres = urlparse(database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': tmpPostgres.path.replace('/', ''),
            'USER': tmpPostgres.username,
            'PASSWORD': tmpPostgres.password,
            'HOST': tmpPostgres.hostname,
            'PORT': tmpPostgres.port or 5432, # Safely falls back to 5432 if omitted
            'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
        }
    }
else:
    # 3. If the URL is empty or missing, fallback to local SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ==========================================
# ALLAUTH HEADLESS SETTINGS
# ==========================================
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['username', 'email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[arvebCRM] '

HEADLESS_ONLY = True
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": "http://localhost:3000/verify-email/{key}",
    "account_reset_password_from_key": "hhttp://localhost:3000/password-reset/{key}",
}

HEADLESS_ADAPTER = 'api.adapters.CustomHeadlessAdapter'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

if ON_RAILWAY:
    CSRF_TRUSTED_ORIGINS = [
        'https://*.railway.app',
        'http://*.railway.app',
        ]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_BASE_DIR = BASE_DIR / 'staticfiles'
STATICFILES_BASE_DIR.mkdir(exist_ok=True, parents=True)

STATICFILES_VENDOR_DIR = STATICFILES_BASE_DIR / 'vendors'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# source (s) for python manage.py collectstatic
STATICFILES_DIRS = [
    STATICFILES_BASE_DIR
]

# output for python manage.py collectstatic
# local cdn --> prod cdn
STATIC_ROOT = BASE_DIR / 'local-cdn'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# ==========================================
# CORS & CSRF CONFIGURATION (Dynamic)
# ==========================================
# ALLAUTH_HEADLESS_USER_SERIALIZER = "api.serializers.UserSerializer"

CORS_ALLOW_CREDENTIALS = True

# Default: Localhost
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# CRITICAL: Custom User Model
AUTH_USER_MODEL = 'api.User'

# Codespace Overrides
if ON_CODESPACE:
    codespace_name = os.getenv("CODESPACE_NAME")
    codespace_domain = os.getenv("GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN")
    
    if codespace_name and codespace_domain:
        # Frontend (React) running on port 5173
        frontend_url = f"https://{codespace_name}-5173.{codespace_domain}"
        CORS_ALLOWED_ORIGINS.append(frontend_url)
        
        # Backend (Django) running on port 8000 - Needed for Admin CSRF
        backend_url = f"https://{codespace_name}-8000.{codespace_domain}"
        CSRF_TRUSTED_ORIGINS.append(backend_url)

    # Tells Django to read the proxy headers from Codespaces to construct URLs properly
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    INSTALLED_APPS += [
        'django_browser_reload',
    ]
    MIDDLEWARE += [
        'django_browser_reload.middleware.BrowserReloadMiddleware',
    ]
    X_FRAME_OPTIONS = 'ALLOW-FROM preview.app.github.dev'
    ALLOWED_HOSTS += [
        '.app.github.dev',
    ]

REST_FRAMEWORK = {

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', # For guests (Login page)
        'rest_framework.throttling.UserRateThrottle'  # For logged-in users
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/minute',   # Max 10 login attempts per min (Anti-Brute Force)
        'user': '1000/day',    # Max 1000 API calls per day (Anti-Spam)
    }
}